version: '3.8'

services:
  n8n:
    # image: docker.n8n.io/n8nio/n8n:latest
    image: n8nio/n8n:latest
    container_name: idras_n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Asia/Ho_Chi_Minh
      - TZ=Asia/Ho_Chi_Minh
      - N8N_HOST=localhost
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      - N8N_EDITOR_BASE_URL=http://localhost:5678/
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
    volumes:
      # Nơi n8n lưu trữ database và cấu hình (không bị mất khi tắt container)
      - n8n_data:/home/node/.n8n
      # Map thư mục n8n-workflows ở ngoài máy thật vào trong container
      - ./n8n-workflows:/home/node/n8n-workflows

volumes:
  n8n_data: